### ISSUE TITLE
Выбрать провайдера карт

### ISSUE THREAD

**Issue by kislovs** [map-sharing/Description#6]

**Comment by Arishenk** [comment]
https://tech.yandex.ru/maps/doc/jsapi/2.1/terms/index-docpage/#index__conditions

**Comment by kislovs** [comment]
В Google Maps ограничение в 10 точек в одном маршруте :с

Google Maps позволяют расшарить маршрут или вставить карту с этим маршрутом:
![image](https://user-images.githubusercontent.com/21275299/55678342-19e97080-5922-11e9-8c1f-7001e878ddf7.png)
![image](https://user-images.githubusercontent.com/21275299/55678347-266dc900-5922-11e9-9800-970c0b3e2eb4.png)
![image](https://user-images.githubusercontent.com/21275299/55678352-35ed1200-5922-11e9-953c-549c2244e878.png)

**Comment by kislovs** [comment]
Хотя, вроде бы есть способ обойти ограничение в 10 точек:
https://www.youtube.com/watch?v=tlmUJ8-KQ5o

**Comment by kislovs** [comment]
https://leafletjs.com/ гляньте чуть подробнее на вот это всё-таки
Как я понимаю, на связке leafletjs + openstreetmap + некоторые плагинчики мы сможем сделать всё, что планируем + это будет полностью бесплатно + оно очень кастомизируемое (на первый взгляд)

**Comment by kislovs** [comment]
Либо на вот это: https://openlayers.org/
Основное отличие от leafletjs - куча функционала из коробки, в отличие от leafletjs, где из коробки идёт минимум, а расширение идёт за счёт плагинов

**Comment by ololo-zen** [comment]
Выбрали OSM, Leaflet.js
