### ISSUE TITLE
Описание договора об API

### ISSUE THREAD

**Issue by kislovs** [map-sharing/Description#7]
[Swagger.Editor](https://editor.swagger.io)

**Comment by GreoGi** [comment]
https://swagger.io/tools/swagger-editor/

**Comment by GreoGi** [comment]
https://github.com/swagger-api/swagger-editor

**Comment by GreoGi** [comment]
Как я понял, можно локально установить и пользоваться, можно онлайн. Использует OpenAPI, надо будет о нём почитать тоже

**Comment by GreoGi** [comment]
Ознакомительная статья
https://habr.com/ru/post/322460/

**Comment by GreoGi** [comment]
getting started with swagger
https://swagger.io/tools/open-source/getting-started/

**Comment by GreoGi** [comment]
Документация
https://swagger.io/docs/

**Comment by GreoGi** [comment]
Создание документации по уже существующему API
https://swagger.io/resources/articles/documenting-apis-with-swagger/

**Comment by GreoGi** [comment]
способ делать это через код бэкенда
https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started

**Comment by GreoGi** [comment]
О способах документирования API через swagger
https://swagger.io/resources/articles/documenting-apis-with-swagger/

**Comment by GreoGi** [comment]
А теперь забейте на всё, что было выше, можете почитать так, чтобы ознакомится.
Актуальные статьи и прочее снизу

**Comment by GreoGi** [comment]
swashbuckle - прикрученная к swagger'у фича от сообщества, чтобы генерить документацию к API прямо из кода backend'а (В нашем случае ASP.NET Core)

Статьи (И про подключение тоже):
1.    https://habr.com/ru/company/microsoft/blog/325872/
2.    http://flash2048.com/post/using-swagger
3.    https://www.red-gate.com/simple-talk/dotnet/net-development/visual-studio-2017-swagger-building-documenting-web-apis/

Официальные репозитории гитхаба:
1.    https://github.com/domaindrivendev/Swashbuckle
2.    https://github.com/domaindrivendev/Swashbuckle.AspNetCore
